### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by StevenNunez** [JoshCheek/atom-seeing-is-believing#13]
[Enter steps to reproduce below:]

1. create file named test.rb
2. Add `1 + 1 # =>`
3. Press command + Option + N
4. Enjoy explosion

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [seeing-is-believing](https://github.com/JoshCheek/atom-seeing-is-believing) package, v1.5.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/StevenNunez/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:59

TypeError: undefined is not a function
    at ChildProcess.<anonymous> (/Users/StevenNunez/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:61:29)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:997:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1070:5)
```

### Commands

```
     -0:06.0 vim-mode:till (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:05.9 blur (atom-text-editor.editor.mini.is-focused)
  2x -0:05.6 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:05.1 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.1 seeing-is-believing:annotate-magic-comments (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "soda-light-ui",
      "solarized-light-syntax"
    ]
  },
  "seeing-is-believing": {
    "add-to-env": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-handlebars, v0.4.0
autocomplete-emojis, v1.0.0
dash, v1.1.0
ember-cli-helper, v0.7.2
ember-snippets, v1.0.0
emmet, v2.3.6
javascript-snippets, v1.0.0
language-elixir, v0.4.0
language-ember-script, v0.1.0
language-jade, v0.3.0
language-rspec, v0.3.0
language-stylus, v0.1.0
linter-handlebars, v0.1.1
seeing-is-believing, v1.5.0
soda-light-ui, v0.2.0
vim-mode, v0.42.0

# Dev
No dev packages
```

**Comment by StevenNunez** [comment]
Killed bunch of plugins. Same steps

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [seeing-is-believing](https://github.com/JoshCheek/atom-seeing-is-believing) package, v1.5.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/StevenNunez/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:59

TypeError: undefined is not a function
    at ChildProcess.<anonymous> (/Users/StevenNunez/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:61:29)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:997:16)
    at Socket.<anonymous> (child_process.js:1166:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
```

### Commands

```
     -0:00.8 seeing-is-believing:annotate-magic-comments (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax-modified"
    ],
    "disabledPackages": [
      "language-mustache",
      "timecop"
    ]
  },
  "seeing-is-believing": {
    "add-to-env": {}
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.6
language-elixir, v0.4.0
language-rspec, v0.3.0
seeing-is-believing, v1.5.0
solarized-light-syntax-modified, v0.6.2
vim-mode, v0.42.0

# Dev
No dev packages
```
