### ISSUE TITLE
Uncaught TypeError: Cannot read property 'seeing-is-believing' of undefined

### ISSUE THREAD

**Issue by danwise91** [JoshCheek/atom-seeing-is-believing#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: [seeing-is-believing](https://github.com/JoshCheek/atom-seeing-is-believing) package, v1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'seeing-is-believing' of undefined

```
At /Users/danielwise/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:89

TypeError: Cannot read property 'seeing-is-believing' of undefined
    at Object.module.exports.SeeingIsBelieving.getVars (/Users/danielwise/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:89:5)
    at Object.module.exports.SeeingIsBelieving.annotateDocument (/Users/danielwise/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:139:17)
    at atom-workspace.subscriptions.add.atom.commands.add.seeing-is-believing:annotate-document (/Users/danielwise/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:28:58)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.9.0 seeing-is-believing:annotate-document (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
seeing-is-believing, v1.7.0

# Dev
No dev packages
```

**Comment by JoshCheek** [comment]
Should be fixed now: Make sure you have the latest Atom and update your SiB.
