### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add-to-env' of undefined

### ISSUE THREAD

**Issue by kirangp** [JoshCheek/atom-seeing-is-believing#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [seeing-is-believing](https://github.com/JoshCheek/atom-seeing-is-believing) package, v1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'add-to-env' of undefined

```
At /Users/avinashprassad/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:89

TypeError: Cannot read property 'add-to-env' of undefined
    at Object.module.exports.SeeingIsBelieving.getVars (/Users/avinashprassad/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:89:5)
    at Object.module.exports.SeeingIsBelieving.annotateDocument (/Users/avinashprassad/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:139:17)
    at atom-workspace.subscriptions.add.atom.commands.add.seeing-is-believing:annotate-document (/Users/avinashprassad/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:28:58)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
 13x -6:06.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -6:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
 18x -5:59.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:56.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:48.1.0 core:paste (atom-text-editor.editor.is-focused)
  8x -5:45 core:save (atom-text-editor.editor.is-focused)
     -5:39 core:delete (atom-text-editor.editor.is-focused)
  2x -5:26.6.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -5:25.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:13.1.0 seeing-is-believing:annotate-magic-comments (atom-text-editor.editor.is-focused)
     -3:39 editor:newline (atom-text-editor.editor.is-focused)
     -3:37.6.0 core:paste (atom-text-editor.editor.is-focused)
  4x -3:35.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:20.9.0 seeing-is-believing:annotate-document (atom-text-editor.editor.is-focused)
     -0:07.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.0 seeing-is-believing:annotate-document (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.7.2
autocomplete-ruby, v0.1.0
highlight-selected, v0.11.2
linter, v1.11.4
linter-ruby, v1.2.2
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
pigments, v0.24.5
seeing-is-believing, v1.7.0

# Dev
No dev packages
```

**Comment by kirangp** [comment]
this is my config file

"*":
  core: {}
  editor:
    fontSize: 17
    invisibles: {}
  "exception-reporting":
    userId: "d78c1c82-0729-5176-46ac-7c51a43fef45"
  minimap:
    plugins:
      "highlight-selected": true
      "highlight-selectedDecorationsZIndex": 0
  welcome:
    showOnStartup: false
"seeing-is-believing":
  "ruby-command": "/Users/avinashprassad/.rvm/bin/sib_ruby"
  "add-to-env":
      SHELL: "/bin/bash"

**Comment by Edozie101** [comment]
I still have this issue with this
