### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by doubleh2** [JoshCheek/atom-seeing-is-believing#27]
having trouble installing on Atom (1.12.4) for Mac osx (10.12.1)
1) when I install package within Atom I get:
`'seeing_is_believing' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`
2) when I install from command line and run in Atom I get:
`/Library/Ruby/Gems/2.0.0/gems/seeing_is_believing-3.1.0/lib/seeing_is_believing/event_stream/consumer.rb:59:in `fix_encoding': undefined method `scrub' for "2.0.0":String (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/seeing_is_believing-3.1.0/lib/seeing_is_believing/event_stream/consumer.rb:168:in `extract_string'
	from /Library/Ruby/Gems/2.0.0/gems/seeing_is_believing-3.1.0/lib/seeing_is_believing/event_stream/consumer.rb:199:in `event_for'
	from /Library/Ruby/Gems/2.0.0/gems/seeing_is_believing-3.1.0/lib/seeing_is_believing/event_stream/consumer.rb:143:in `next_event'
	from /Library/Ruby/Gems/2.0.0/gems/seeing_is_believing-3.1.0/lib/seeing_is_believing/event_stream/consumer.rb:106:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/seeing_is_believing-3.1.0/lib/seeing_is_believing/event_stream/consumer.rb:112:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/seeing_is_believing-3.1.0/lib/seeing_is_believing/evaluate_by_moving_files.rb:133:in `block in evaluate_file'
`

**Comment by JoshCheek** [comment]
To fix
------

Install SiB again at the command line, it should install version 3.1.1 which should work (I just released it to fix this).


Background
------------

My bad on this, I thought `scrub` was 1.9.3 only. Since I stopped supporting 1.9.3, I removed some code that I thought I didn't need anymore https://github.com/JoshCheek/seeing_is_believing/commit/6ffd6c36dab959330b59de48367380594843c3e7

That didn't fail CI b/c I'd gotten irritated w/ intermittent / nondeterministic CI failures and wound up removing support for 2.0 since it's a pretty iffy Ruby version and it was [EOL'd back in Feb](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/). But that was dumb since that's what Mac ships w/, and my CI failures were due to threading and IO, not v2.0.

So, [reverted that commit](https://github.com/JoshCheek/seeing_is_believing/commit/065d0e2558a9a180cef5745ff4663ed8b1ee6913) and [added 2.0.0](https://github.com/JoshCheek/seeing_is_believing/commit/25dba5c2aef6fe0cd60918916b5fd69713c6f67e) back to the CI build to catch stuff like that in the future. 

[CI passes](https://travis-ci.org/JoshCheek/seeing_is_believing/builds/177249287) with the current code on 2.0.0

**Comment by doubleh2** [comment]
Thanks Josh, 

I don’t see the update yet (still only see 2.1.0 from 22 days ago), but I’ll keep an eye out for it. 

 

https://github.com/JoshCheek/atom-seeing-is-believing/releases

 

HH

**Comment by doubleh2** [comment]
Update, I just downloaded SiB 2.1.0 to my  /Users/<me>/.atom/packages folder and it works perfect

 

HH

**Comment by JoshCheek** [comment]
Hey, if you still use this lib, then do you still use Ruby 2.0? It's rough to maintain compatibility with b/c it's got a lot of little incompatibilities and I can't install it at this point. So I'm thinking about removing support for it again.

Seems reasonable since it was EOL'd in Feb 2016:

> As it has been announced before, all support for Ruby 2.0.0 has ended today. Bug and security fixes from more recent Ruby versions will no longer be backported to 2.0.0, and no further patch release of 2.0.0 will be released.
>
> -- https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/
